DMXKingUltraDMXPro {
  options: {},
  universe: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 463 more bytes>,
  sendDMXReq: 6,
  dev: SerialPort {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 65536,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: null,
      ended: false,
      endEmitted: false,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: true,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 65536,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 0,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    allowHalfOpen: true,
    binding: DarwinBinding {
      bindingOptions: [Object],
      fd: null,
      writeOperation: null,
      openOptions: [Object]
    },
    path: '/dev/tty.usbserial-6A009092',
    settings: {
      autoOpen: true,
      baudRate: 250000,
      dataBits: 8,
      hupcl: true,
      lock: true,
      parity: 'none',
      rtscts: false,
      stopBits: 2,
      xany: false,
      xoff: false,
      xon: false,
      highWaterMark: 65536
    },
    opening: true,
    closing: false,
    _pool: <Buffer 60 8e 61 02 01 00 00 00 00 60 32 04 01 00 00 00 d0 03 01 00 00 00 00 00 bc 00 00 00 c4 00 00 00 e0 cf 32 04 01 00 00 00 bc 00 00 00 c4 00 00 00 60 87 ... 65486 more bytes, used: 0>,
    _kMinPoolSpace: 128
  },
  _events: [Object: null prototype] { update: [Function] },
  _eventsCount: 1
}
DMXKingUltraDMXPro {
  options: {},
  universe: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... 463 more bytes>,
  sendDMXReq: 6,
  dev: SerialPort {
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 65536,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: null,
      pipesCount: 0,
      flowing: null,
      ended: false,
      endEmitted: false,
      reading: false,
      sync: true,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      paused: true,
      emitClose: true,
      autoDestroy: false,
      destroyed: false,
      defaultEncoding: 'utf8',
      awaitDrain: 0,
      readingMore: false,
      decoder: null,
      encoding: null
    },
    readable: true,
    _events: [Object: null prototype] { open: [Function] },
    _eventsCount: 1,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 65536,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 518,
      writing: true,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: [Function: nop],
      writelen: 518,
      bufferedRequest: null,
      lastBufferedRequest: null,
      pendingcb: 1,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: false,
      bufferedRequestCount: 0,
      corkedRequestsFree: [Object]
    },
    writable: true,
    allowHalfOpen: true,
    binding: DarwinBinding {
      bindingOptions: [Object],
      fd: null,
      writeOperation: null,
      openOptions: [Object]
    },
    path: '/dev/tty.usbserial-6A009092',
    settings: {
      autoOpen: true,
      baudRate: 250000,
      dataBits: 8,
      hupcl: true,
      lock: true,
      parity: 'none',
      rtscts: false,
      stopBits: 2,
      xany: false,
      xoff: false,
      xon: false,
      highWaterMark: 65536
    },
    opening: true,
    closing: false,
    _pool: <Buffer 60 8e 61 02 01 00 00 00 00 60 32 04 01 00 00 00 d0 03 01 00 00 00 00 00 bc 00 00 00 c4 00 00 00 e0 cf 32 04 01 00 00 00 bc 00 00 00 c4 00 00 00 60 87 ... 65486 more bytes, used: 0>,
    _kMinPoolSpace: 128
  },
  _events: [Object: null prototype] { update: [Function] },
  _eventsCount: 1
}
